name: SonarQube Scan (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python # or your build environment
        uses: actions/setup-python@v4 # or other setup action
        with:
          python-version: '3.13' # or your version

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
